const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f4f4f8",
    cardForeground: "#0a0a0a",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#ede9fe",
    secondaryForeground: "#3b0764",
    muted: "#f0eeff",
    mutedForeground: "#6b6b8a",
    accent: "#3B82F6",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e4e0f0",
    input: "#f0eeff",
  },
  dark: {
    text: "#F0F0F5",
    tint: "#8B5CF6",
    background: "#080810",
    foreground: "#F0F0F5",
    card: "#10101C",
    cardForeground: "#F0F0F5",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2E",
    secondaryForeground: "#A0A0C0",
    muted: "#141420",
    mutedForeground: "#5A5A7A",
    accent: "#3B82F6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E30",
    input: "#141420",
  },
  radius: 14,
};

export default colors;
