kind = "mobile"
previewPath = "/"
title = "Logo Store"
version = "1.0.0"
id = "artifacts/logo-store"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18951

[services.development]
run = "pnpm --filter @workspace/logo-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/logo-store", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/logo-store", "run", "serve" ]

[services.env]
PORT = "18951"
BASE_PATH = "/"
